services:
  mysql:
    image: mysql:8.4
    container_name: kanoa-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanoa
      MYSQL_USER: kanoa
      MYSQL_PASSWORD: kanoa

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
